### ISSUE TITLE
UMLS 2022 IndexError: list index out of range

### ISSUE THREAD

**Issue by devfoo-one** [DATEXIS/UMLSParser#9]
umls-2022AB-full.zip

```
umls = UMLSParser('/home/toberhauser/DEV/Data/UMLS/2022_test/umls-extract')
```

```
INFO:umlsparser.UMLSParser:Initialising UMLSParser for basepath /home/toberhauser/DEV/Data/UMLS/2022_test/umls-extract
INFO:umlsparser.UMLSParser:No language filtering applied.
Parsing UMLS concepts (MRCONSO.RRF): 16761432it [01:42, 163714.10it/s]
Traceback (most recent call last):
  File "/home/toberhauser/DEV/GENERAL_PLAYGROUND/UMLS/2022_test.py", line 3, in <module>
    umls = UMLSParser('/home/toberhauser/DEV/Data/UMLS/2022_test/umls-extract')
  File "/home/toberhauser/DEV/GENERAL_PLAYGROUND/venv/lib/python3.8/site-packages/umlsparser/UMLSParser.py", line 54, in __init__
    self.__parse_mrconso__()
  File "/home/toberhauser/DEV/GENERAL_PLAYGROUND/venv/lib/python3.8/site-packages/umlsparser/UMLSParser.py", line 88, in __parse_mrconso__
    'SRL': line[15],
```

**Comment by devfoo-one** [comment]
![image](https://user-images.githubusercontent.com/5645199/221569166-9cabf31d-c234-42c4-b1b8-5a55f7042aa5.png)

MRCONSO.RRF ends with a corrupted line.

**Comment by devfoo-one** [comment]
![image](https://user-images.githubusercontent.com/5645199/221570168-11807dab-22c8-4986-9624-9344e57aff4c.png)

**Comment by devfoo-one** [comment]
2019AB:

![image](https://user-images.githubusercontent.com/5645199/221571239-d9bb595e-89f6-4cb0-a491-77ba2750f965.png)

**Comment by devfoo-one** [comment]
UMLS2022 contains 3 MRCONSO splits!

![image](https://user-images.githubusercontent.com/5645199/221573520-3fc1cd03-9c2b-4678-80b5-a2c6c784bab3.png)
